# Args: <PATH_TO_3D-Front_json> <PATH_TO_3D-Future-model> <output>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:2>",
          "max_bounces": 0,
          "diffuse_bounces": 0,
          "glossy_bounces": 0,
          "transmission_bounces": 0,
          "transparency_bounces": 0
        }
      }
    },
    {
      "module": "loader.Front3DLoader",
      "config": {
        "json_path": "<args:0>",
        "3D_future_model_path": "<args:1>"
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
      }
    },
    {
      "module": "camera.Front3DCameraSampler",
      "config": {
        "amount_of_objects_needed_per_room": 4,
        "sample_noise": True,
        "r_max": 5.0,
        "t_max": 0.05,
        "intrinsics": {
          "resolution_x": 256,
          "resolution_y": 256,
        }
        "cam_poses": [
          {
            "number_of_samples": 1,
            "min_interest_score": 0.5,
            "proximity_checks": {
              "min": 1.0,
              "avg": {
                "min": 1.0,
                "max": 4.0,
              },
              "no_background": True
            },
            "location": {
              "provider":"sampler.Uniform3d",
              "max":[0, 0, 1.8],
              "min":[0, 0, 1.4]
            },
            "rotation": {
              "value": {
                "provider":"sampler.Uniform3d",
                "max":[1.338, 0, 6.283185307],
                "min":[1.2217, 0, 0]
              }
            }
          }
        ]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 350,
        "render_normals": False,
        #"auto_tile_size": False,
        #"tile_x": 1,
        #"tile_y": 1,
        "simplify_subdivision_render": 1,
        "cpu_threads": 8
      }
    },
    {
      "module": "renderer.UVRenderer",
      "config": {
        "output_key": "uvmap",
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": ["class", "instance", "name", "uid"],
        "default_values": {"uid": "$$None$$"}
      }
    },
    {
      "module": "writer.CameraStateWriter",
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "depth": [
            {
              "module": "postprocessing.TrimRedundantChannels",
            }
          ]
        }
      }
    },
    {
      "module": "writer.SceneWriter",
    }
  ]
}

