# Args: <PATH_TO_3D-Front_json> <PATH_TO_3D-Future-model> <CC_Material_path> <output>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:3>",
          "max_bounces": 0,
          "diffuse_bounces": 0,
          "glossy_bounces": 0,
          "transmission_bounces": 0,
          "transparency_bounces": 0
        }
      }
    },
    {
      "module": "loader.Front3DLoader",
      "config": {
        "json_path": "<args:0>",
        "3D_future_model_path": "<args:1>"
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
      }
    },
    {
      "module": "loader.CCMaterialLoader",
      "config": {
        "folder_path": "<args:2>",
        "used_assets": ["Bricks", "Wood", "Carpet", "Tile", "Marble"]
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Floor.*"
          }
        },
        "cf_randomize_materials": {
          "randomization_level": 0.95,
          "materials_to_replace_with": {
            "provider": "getter.Material",
            "random_samples": 1,
            "conditions": {
              "cp_is_cc_texture": True
            }
          }
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Wall.*"
          }
        },
        "cf_randomize_materials": {
          "randomization_level": 0.2,
          "materials_to_replace_with": {
            "provider": "getter.Material",
            "random_samples": 1,
            "conditions": {
              "cp_is_cc_texture": True,
              "cp_asset_name": "Marble.*"
            }
          }
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Wall.*"
          }
        },
        "cf_randomize_materials": {
          "randomization_level": 0.1,
          "materials_to_replace_with": {
            "provider": "getter.Material",
            "random_samples": 1,
            "conditions": {
              "cp_is_cc_texture": True,
              "cp_asset_name": "Wood.*"
            }
          }
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Baseboard.*"
          }
        },
        "mode": "once_for_all",
        "cf_randomize_materials": {
          "randomization_level": 1.0,
          "materials_to_replace_with": {
            "provider": "getter.Material",
            "random_samples": 1,
            "conditions": {
              "cp_is_cc_texture": True,
              "cp_asset_name": "WoodFloor.*"
            }
          }
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Door.*"
          }
        },
        "mode": "once_for_all",
        "cf_randomize_materials": {
          "randomization_level": 1.0,
          "materials_to_replace_with": {
            "provider": "getter.Material",
            "random_samples": 1,
            "conditions": {
              "cp_is_cc_texture": True,
              "cp_asset_name": "WoodFloor.*"
            }
          }
        }
      }
    },
    {
      "module": "camera.Front3DCameraSampler",
      "config": {
        "amount_of_objects_needed_per_room": 6,
        "sample_noise": True,
        "r_max": 5.0,
        "t_max": 0.05,
        "intrinsics": {
          "resolution_x": 512,
          "resolution_y": 512,
        },
        "cam_poses": [
          {
            "number_of_samples": 300,
            "max_tries": 10000000, # 10 million, default is 100 million
            "min_interest_score": 0.3,
            "proximity_checks": {
              "min": 0.5,
              "avg": {
                "min": 0.5,
                "max": 4.0,
              },
              "no_background": True
            },
            "location": {
              "provider":"sampler.Uniform3d",
              "max":[0, 0, 1.8],
              "min":[0, 0, 1.4]
            },
            "rotation": {
              "value": {
                "provider":"sampler.Uniform3d",
                "max":[1.4, 0, 6.283185307],
                "min":[1.1, 0, 0]
              }
            }
          }
        ]
      }
    },
    {
      "module": "manipulators.UVManipulator",
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 350,
        "render_normals": True,
        "normals_output_key": "normals",
        "render_distance": True,
        "distance_output_key": "distance",
        "simplify_subdivision_render": 1,
        "cpu_threads": 8
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": [ "class", "instance", "name", "uid" ],
        "default_values": { "uid": "$$None$$" }
      }
    },
    {
      "module": "renderer.UVRenderer",
      "config": {
        "output_key": "uvmap",
      }
    },
    {
      "module": "writer.CameraStateWriter",
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "depth": [
            {
              "module": "postprocessing.TrimRedundantChannels",
            }
          ]
        }
      }
    },
    {
      "module": "writer.SceneWriter",
    }
  ]
}
